"""Score a message writer on every labelled file that goes back to a customer.

The route half of the agent is scored by `harness.py`. This scores the model
half, and asks the questions that decide whether a model is worth paying for:

  - how often is its first draft sendable as written?
  - how often does the retry rescue it?
  - how often does the customer get the template anyway?
  - how long does it take, and how many tokens?

A writer whose drafts keep falling back to the template is not delivering, and
by the posting's own rule should be removed.
"""

from __future__ import annotations

import statistics
import time
from dataclasses import dataclass
from pathlib import Path

from preflight.config import Config, load_config
from preflight.explain import Draft, Writer
from preflight.pipeline import run
from preflight.types import State

from .dataset import CASES, Case, build


@dataclass(frozen=True)
class Row:
    case: Case
    draft: Draft


def run_messages(
    out_dir: str | Path,
    writer: Writer | None,
    config: Config | None = None,
    delay_s: float = 0.0,
    only: str | None = None,
) -> list[Row]:
    out_dir = Path(out_dir)
    if not (out_dir / "labels.yaml").exists():
        build(out_dir)
    config = config or load_config()
    rows = []
    for case in CASES:
        if case.expect_route is not State.NEEDS_CUSTOMER_FIX:
            continue
        if only and only not in case.name:
            continue
        result = run(out_dir / case.filename, case.product, config=config, draft=True, writer=writer)
        if result.message is not None:
            rows.append(Row(case, result.message))
            print(f"  {case.name:<26} {result.message.source}", flush=True)
        if delay_s:
            time.sleep(delay_s)  # free tiers limit requests per minute
    return rows


def _share(n: int, total: int) -> str:
    return f"{n} of {total} ({n / total * 100:.0f}%)" if total else "n/a"


def render(rows: list[Row]) -> str:
    total = len(rows)
    writer = rows[0].draft.writer if rows else "none"
    first = sum(1 for r in rows if r.draft.attempts and r.draft.attempts[0].passed)
    retried = sum(1 for r in rows if r.draft.source == "model" and len(r.draft.attempts) > 1)
    fallback = sum(1 for r in rows if r.draft.source == "fallback")
    errors = sum(1 for r in rows if any(a.error for a in r.draft.attempts))
    calls = [a for r in rows for a in r.draft.attempts if not a.error]
    ms = [a.elapsed_ms for a in calls]
    tok_in = [a.tokens_in for a in calls if a.tokens_in is not None]
    tok_out = [a.tokens_out for a in calls if a.tokens_out is not None]

    lines = [
        f"# Message writer: `{writer}`",
        "",
        "Generated by `python -m evalkit messages`. Every file in the labelled set that",
        "should go back to the customer is run through the pipeline, and the writer is",
        "asked for a message. The guard in `preflight/explain/guard.py` decides whether",
        "each draft may be sent.",
        "",
        "| | |",
        "|---|---:|",
        f"| Files | {total} |",
        f"| First draft passed the guard | {_share(first, total)} |",
        f"| Passed after one retry | {_share(retried, total)} |",
        f"| Fell back to the template | {_share(fallback, total)} |",
        f"| Of which the model could not be reached | {errors} |",
        f"| Model calls | {len(calls)} |",
    ]
    if ms:
        lines.append(f"| Median time per call | {statistics.median(ms) / 1000:.1f} s |")
    if tok_in and tok_out:
        lines.append(
            f"| Mean tokens per call, in / out | {statistics.mean(tok_in):.0f} / "
            f"{statistics.mean(tok_out):.0f} |"
        )

    rejected = [(r, a) for r in rows for a in r.draft.attempts if a.problems]
    lines += ["", "## What the guard rejected", ""]
    if not rejected:
        lines.append("Nothing. No draft the model returned was refused.")
    for row, attempt in rejected:
        lines.append(f"- **{row.case.name}**: " + "; ".join(attempt.problems))

    failed = [(r, a) for r in rows for a in r.draft.attempts if a.error]
    if failed:
        lines += ["", "## Calls that failed", ""]
        lines += [f"- **{r.case.name}**: {a.error}" for r, a in failed]

    lines += ["", "## The messages that would be sent", ""]
    for row in rows:
        who = {"model": "model", "template": "template", "fallback": "template (fallback)"}
        lines += [f"### {row.case.name} ({who[row.draft.source]})", ""]
        lines += [f"> {line}" if line else ">" for line in row.draft.text.splitlines()]
        lines.append("")

    lines += [
        "## How to read this",
        "",
        "- The guard checks numbers, coverage, invented problems and promises. It",
        "  does not judge tone or whether the advice is well explained; read the",
        "  messages above for that.",
        "- Model output varies from run to run. One run of 20 files is a sample,",
        "  not a rate.",
        "- The files are synthetic, like the rest of the labelled set.",
    ]
    return "\n".join(lines)
