"""Render a Report as markdown, including the parts that look bad."""

from __future__ import annotations

from preflight.types import State

from .harness import Report

ROUTES = (State.APPROVED, State.NEEDS_CUSTOMER_FIX, State.HUMAN_REVIEW, State.REJECTED)
SHORT = {
    State.APPROVED: "approved",
    State.NEEDS_CUSTOMER_FIX: "customer fix",
    State.HUMAN_REVIEW: "human review",
    State.REJECTED: "rejected",
}


def _pct(value: float | None) -> str:
    return "n/a" if value is None else f"{value * 100:.0f}%"


# Printed with every report so it cannot drift away from the numbers it
# qualifies. A results table without this paragraph overstates what was proven.
CAVEAT = """### How to read these numbers

- **The set is synthetic.** Every file is generated by `evalkit/art.py`: hard
  edges, flat colour, no photographic noise unless asked for. Real customer
  uploads are messier, so these rates are an optimistic bound, not a forecast.
  No real artwork has been run through this agent yet.
- **Parts of the agent were changed in response to failures in this very set,
  so those parts are scored in-sample.** `ALPHA_FAKE` moved from four corner
  samples to a perimeter band after `fake_gradient_box` slipped through.
  `DETAIL_AT_CUT` was written after `bleed_flat` was approved on a measurement
  that never happened. What the numbers show is that those cases are handled
  now, not that the agent generalises.
- **Three labels were corrected after a run disagreed with them.** A solid
  block bleeding off an edge is not fine detail; a block corner 0.117 in inside
  a rounded die is genuinely borderline; and a coloured background *is*
  separable, so the geometric check does run on it. Each correction is
  defensible on its own, but correcting labels against output is how a test set
  quietly stops testing anything, so they are named here.
- **36 files is a small sample.** Any rate above carries a confidence interval
  wide enough that only large differences mean anything.
- **Kill criteria, fixed before the numbers existed:** recall below 0.9 on any
  FAIL-severity check, or a non-zero approved-when-it-should-have-been-fixed
  cell, means the agent does not run unsupervised."""


def render(report: Report) -> str:
    lines: list[str] = []
    n = len(report.results)

    lines.append("## Results")
    lines.append("")
    lines.append(
        f"{n} labelled files, generated by `python -m evalkit build`. "
        f"Every number below is reproducible with `python -m evalkit run`."
    )
    lines.append("")
    lines.append(CAVEAT)
    lines.append("")

    # --- per check -----------------------------------------------------
    lines.append("### Per check")
    lines.append("")
    lines.append("Precision and recall are on FAIL severity. A miss reaches the press.")
    lines.append("")
    lines.append("| Check | Cases | Exact severity | Precision | Recall | Misses | False alarms |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for code in sorted(report.checks):
        s = report.checks[code]
        lines.append(
            f"| `{code}` | {s.seen} | {_pct(s.exact_rate)} | {_pct(s.precision)} "
            f"| {_pct(s.recall)} | {s.fn} | {s.fp} |"
        )
    lines.append("")

    # --- per route -----------------------------------------------------
    lines.append("### Per route")
    lines.append("")
    lines.append(f"Route accuracy: **{report.route_accuracy * 100:.0f}%** ({n} files).")
    lines.append("")
    header = " | ".join(SHORT[r] for r in ROUTES)
    lines.append(f"| expected \\ actual | {header} |")
    lines.append("|---|" + "---:|" * len(ROUTES))
    for expected in ROUTES:
        cells = [str(report.confusion.get((expected, actual), 0)) for actual in ROUTES]
        lines.append(f"| **{SHORT[expected]}** | " + " | ".join(cells) + " |")
    lines.append("")

    unsafe = report.unsafe_approvals
    verdict = "**0**" if not unsafe else f"**{len(unsafe)}**"
    lines.append(
        f"Approved when it should have gone back to the customer: {verdict}."
        + ("" if not unsafe else " " + ", ".join(f"`{r.case.name}`" for r in unsafe))
    )
    lines.append("")

    # --- what it got wrong ---------------------------------------------
    wrong = [r for r in report.results if not (r.route_ok and r.findings_ok)]
    lines.append("### Where it is wrong")
    lines.append("")
    if not wrong:
        lines.append("Nothing in this set. The set is small and synthetic; see the limits.")
    else:
        lines.append("| Case | Expected | Actual | Disagreement | Why |")
        lines.append("|---|---|---|---|---|")
        for r in wrong:
            diffs = (
                ", ".join(f"`{c}` {w} -> {g}" for c, w, g in r.disagreements()) or "route only"
            )
            flag = " *(known limitation)*" if r.case.known_limitation else ""
            lines.append(
                f"| `{r.case.name}` | {SHORT[r.case.expect_route]} "
                f"| {SHORT[r.actual_route]} | {diffs} | {r.case.note}{flag} |"
            )
    lines.append("")

    # --- speed ---------------------------------------------------------
    lines.append("### Speed")
    lines.append("")
    lines.append(
        f"Deterministic pipeline, per file: p50 **{report.percentile(50):.0f} ms**, "
        f"p95 **{report.percentile(95):.0f} ms**, max {report.latencies.max():.0f} ms. "
        f"No model calls are involved in any verdict."
    )
    lines.append("")

    return "\n".join(lines)
